// AUTO-GENERATED by apps/web/scripts/build-api-docs.mjs — do not edit by hand.
// Regenerate with `pnpm --filter tablecn-web api:build`.

export interface ApiMember {
  name: string
  type: string
  required: boolean
  default: string | null
  description: string
}

export const useDataTableOptions: ApiMember[] = [
  {
    "name": "localization",
    "type": "Partial<DataTableLocalization>",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "icons",
    "type": "Partial<DataTableIcons>",
    "required": false,
    "default": null,
    "description": "Override any subset of the table's icons."
  },
  {
    "name": "defaultDensity",
    "type": "Density",
    "required": false,
    "default": "\"comfortable\"",
    "description": "Initial density. Uncontrolled."
  },
  {
    "name": "defaultShowColumnFilters",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Initially show the filter row. Uncontrolled."
  },
  {
    "name": "isLoading",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": ""
  },
  {
    "name": "enableColumnActions",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enableColumnFilterModes",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the filter-mode menu adornment on filter fields. Default true."
  },
  {
    "name": "enableFilterMatchHighlighting",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Highlight matched substrings in cells. Default true."
  },
  {
    "name": "enableGlobalFilter",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the expandable global search in the toolbar. Default true."
  },
  {
    "name": "enableGlobalFilterModes",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the global search mode menu (fuzzy/contains/…). Default true."
  },
  {
    "name": "defaultGlobalFilterMode",
    "type": "GlobalFilterMode",
    "required": false,
    "default": "\"fuzzy\"",
    "description": "Initial global search mode. Default \"fuzzy\"."
  },
  {
    "name": "enableColumnOrdering",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Drag-and-drop column reordering (adds a grip to each header)."
  },
  {
    "name": "enableColumnPinning",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Column pinning (left/right) via the column-actions menu + sticky columns."
  },
  {
    "name": "enableColumnResizing",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Column resizing via an edge drag handle."
  },
  {
    "name": "enableRowOrdering",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Drag-and-drop row reordering (adds a drag-handle column)."
  },
  {
    "name": "enableRowPinning",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Row pinning (top) via a pin toggle in the row-number column."
  },
  {
    "name": "enableRowNumbers",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Adds a leading row-number column."
  },
  {
    "name": "rowNumberMode",
    "type": "\"static\" | \"original\"",
    "required": false,
    "default": "\"static\"",
    "description": "\"static\" tracks the current view (page-aware); \"original\" uses source index."
  },
  {
    "name": "onRowOrderChange",
    "type": "(activeRowId: string, overRowId: string) => void",
    "required": false,
    "default": null,
    "description": "Called on a row drag-and-drop reorder; the consumer reorders its data."
  },
  {
    "name": "enableGrouping",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Row grouping (group-by menu + drop-to-group zone + aggregated group rows)."
  },
  {
    "name": "enableExpanding",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Row expansion (tree sub-rows and/or detail panels). Auto-on with grouping or when `renderDetailPanel`/`getSubRows` is provided."
  },
  {
    "name": "enableStickyFooter",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Pin the footer (aggregation/footer cells) to the bottom of the surface. Default true (matches the sticky header)."
  },
  {
    "name": "renderDetailPanel",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Render an expanding detail panel for each row."
  },
  {
    "name": "enableEditing",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Enable inline editing."
  },
  {
    "name": "editDisplayMode",
    "type": "EditDisplayMode",
    "required": false,
    "default": "\"cell\"",
    "description": "How edits are surfaced. Default \"cell\"."
  },
  {
    "name": "createRowDefaults",
    "type": "Record<string, unknown>",
    "required": false,
    "default": null,
    "description": "Default values for the create form, keyed by column id."
  },
  {
    "name": "enableClickToCopy",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Show a click-to-copy affordance on all cells (per-column override via meta)."
  },
  {
    "name": "onEditCellSave",
    "type": "(props: { row: Row<TData> column: Column<TData, unknown> value: unknown table: DataTableInstance<TData> }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onSaveRow",
    "type": "(props: { row: Row<TData> values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCreateRow",
    "type": "(props: { values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderRowActions",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderCellActionMenuItems",
    "type": "(props: { cell: Cell<TData, unknown> row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onRowClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": "Fired when a body row is clicked / double-clicked."
  },
  {
    "name": "onRowDoubleClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCellClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": "Fired when a body cell is clicked / double-clicked."
  },
  {
    "name": "onCellDoubleClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowVirtualization",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Virtualize body rows for large datasets (recommended past ~100 rows). The table surface becomes the scroll container — give it a bounded height via `className`/`style` (defaults to `max-h-[600px]`). Disables row DnD."
  },
  {
    "name": "enableColumnVirtualization",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Virtualize columns for very wide tables. Applies fixed column widths and is not combined with column pinning/ordering."
  },
  {
    "name": "estimateRowHeight",
    "type": "number",
    "required": false,
    "default": "52",
    "description": "Estimated row height (px) for the virtualizer. Default 52."
  },
  {
    "name": "virtualOverscan",
    "type": "number",
    "required": false,
    "default": "8",
    "description": "Extra rows rendered above/below the viewport. Default 8."
  },
  {
    "name": "enableExport",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Show a CSV/Excel export menu in the toolbar."
  },
  {
    "name": "exportFileName",
    "type": "string",
    "required": false,
    "default": null,
    "description": "Base file name for exports (no extension). Default \"export\"."
  },
  {
    "name": "enableStickyHeader",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enablePagination",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enableTopToolbar",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enableBottomToolbar",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enableKeyboardNavigation",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "title",
    "type": "React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderToolbarActions",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderEmpty",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  }
]

export const columnOptions: ApiMember[] = [
  {
    "name": "variant",
    "type": "FilterVariant",
    "required": false,
    "default": null,
    "description": "Filter UI variant rendered in the filter row. Defaults to \"text\"."
  },
  {
    "name": "options",
    "type": "DataTableFilterOption[]",
    "required": false,
    "default": null,
    "description": "Options for `select` / `multi-select` filter variants. If omitted for a select-style variant, options are derived from faceted unique values."
  },
  {
    "name": "filterMode",
    "type": "FilterMode",
    "required": false,
    "default": null,
    "description": "Default filter mode for this column (overrides the per-variant default)."
  },
  {
    "name": "enableColumnFilterModes",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Per-column override for the filter-mode menu (defaults to the table)."
  },
  {
    "name": "renderColumnFilter",
    "type": "(props: { column: Column<TData, TValue> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom filter UI for this column (escape hatch). Replaces the variant."
  },
  {
    "name": "enableEditing",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Allow editing this column (defaults to true when table editing is on)."
  },
  {
    "name": "editVariant",
    "type": "EditVariant",
    "required": false,
    "default": null,
    "description": "Inline editor variant. Defaults to \"text\"."
  },
  {
    "name": "editSelectOptions",
    "type": "DataTableFilterOption[]",
    "required": false,
    "default": null,
    "description": "Options for the \"select\" edit variant."
  },
  {
    "name": "validate",
    "type": "(value: unknown) => string | undefined",
    "required": false,
    "default": null,
    "description": "Validate an edited value; return an error message or undefined if valid."
  },
  {
    "name": "enableClickToCopy",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Show a click-to-copy affordance on this column's cells."
  },
  {
    "name": "align",
    "type": "\"left\" | \"center\" | \"right\"",
    "required": false,
    "default": null,
    "description": "Horizontal alignment applied to the header label and body cells."
  },
  {
    "name": "disableHighlight",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Opt this column out of match highlighting."
  },
  {
    "name": "disableColumnActions",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Hide the column-actions menu for this column."
  },
  {
    "name": "label",
    "type": "string",
    "required": false,
    "default": null,
    "description": "Human-readable label for menus when the header is not a plain string."
  }
]

export const tableInstance: ApiMember[] = [
  {
    "name": "localization",
    "type": "DataTableLocalization",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "icons",
    "type": "DataTableIcons",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "density",
    "type": "Density",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setDensity",
    "type": "React.Dispatch<React.SetStateAction<Density>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "isFullscreen",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setIsFullscreen",
    "type": "React.Dispatch<React.SetStateAction<boolean>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "showColumnFilters",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setShowColumnFilters",
    "type": "React.Dispatch<React.SetStateAction<boolean>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "columnFilterModes",
    "type": "Record<string, FilterMode>",
    "required": true,
    "default": null,
    "description": "Active filter mode per column id."
  },
  {
    "name": "setColumnFilterMode",
    "type": "(columnId: string, mode: FilterMode) => void",
    "required": true,
    "default": null,
    "description": "Switch a column's filter mode (resets the value when it becomes invalid)."
  },
  {
    "name": "globalFilterMode",
    "type": "GlobalFilterMode",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setGlobalFilterMode",
    "type": "(mode: GlobalFilterMode) => void",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableGlobalFilter",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableGlobalFilterModes",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "isLoading",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnActions",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnFilters",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnFilterModes",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableFilterMatchHighlighting",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "columnsWithCustomCell",
    "type": "ReadonlySet<string>",
    "required": true,
    "default": null,
    "description": "Column ids that supply a custom cell renderer (skipped by auto-highlight)."
  },
  {
    "name": "enableColumnOrdering",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnPinning",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnResizing",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowOrdering",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowPinning",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowNumbers",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "rowNumberMode",
    "type": "\"static\" | \"original\"",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "onRowOrderChange",
    "type": "(activeRowId: string, overRowId: string) => void",
    "required": false,
    "default": null,
    "description": "Called on a row drag-and-drop reorder; the consumer reorders its data."
  },
  {
    "name": "enableGrouping",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableExpanding",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableStickyFooter",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "renderDetailPanel",
    "type": "(props: { row: Row<TData>; table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableEditing",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "editDisplayMode",
    "type": "EditDisplayMode",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "editingCell",
    "type": "EditingCell | null",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setEditingCell",
    "type": "React.Dispatch<React.SetStateAction<EditingCell | null>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "editingRowId",
    "type": "string | null",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "isCreating",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "rowDraft",
    "type": "Record<string, unknown>",
    "required": true,
    "default": null,
    "description": "Draft values for the row/modal editor + create form, keyed by column id."
  },
  {
    "name": "setRowDraftValue",
    "type": "(columnId: string, value: unknown) => void",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "beginRowEdit",
    "type": "(row: Row<TData>) => void",
    "required": true,
    "default": null,
    "description": "Enter row/modal editing for a row, seeding the draft from its values."
  },
  {
    "name": "beginCreate",
    "type": "() => void",
    "required": true,
    "default": null,
    "description": "Open the create form, seeding the draft from `createRowDefaults`."
  },
  {
    "name": "cancelEdit",
    "type": "() => void",
    "required": true,
    "default": null,
    "description": "Exit any editing/creating state, discarding the draft."
  },
  {
    "name": "enableClickToCopy",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "onEditCellSave",
    "type": "(props: { row: Row<TData> column: Column<TData, unknown> value: unknown table: DataTableInstance<TData> }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onSaveRow",
    "type": "(props: { row: Row<TData> values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCreateRow",
    "type": "(props: { values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderRowActions",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderCellActionMenuItems",
    "type": "(props: { cell: Cell<TData, unknown> row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onRowClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onRowDoubleClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCellClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCellDoubleClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowVirtualization",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnVirtualization",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "estimateRowHeight",
    "type": "number",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "virtualOverscan",
    "type": "number",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableExport",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "exportFileName",
    "type": "string",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableStickyHeader",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enablePagination",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowSelection",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableTopToolbar",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableBottomToolbar",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableKeyboardNavigation",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "title",
    "type": "React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderToolbarActions",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderEmpty",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  }
]

export const dataTableProps: ApiMember[] = [
  {
    "name": "table",
    "type": "DataTableInstance<TData>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "pageSizeOptions",
    "type": "number[]",
    "required": false,
    "default": null,
    "description": "Page-size options for the bottom pagination control."
  },
  {
    "name": "surfaceClassName",
    "type": "string",
    "required": false,
    "default": null,
    "description": "Extra classes for the scrollable table surface (e.g. a max-height to engage the sticky header/footer or to bound a virtualized list)."
  }
]

export const localizationKeys: ApiMember[] = [
  {
    "name": "selectAll",
    "type": "string",
    "required": true,
    "default": "Select all",
    "description": ""
  },
  {
    "name": "selectRow",
    "type": "string",
    "required": true,
    "default": "Select row",
    "description": ""
  },
  {
    "name": "clearSelection",
    "type": "string",
    "required": true,
    "default": "Clear selection",
    "description": ""
  },
  {
    "name": "rowsSelected",
    "type": "(selected: number, total: number) => string",
    "required": true,
    "default": "(selected, total) => `${selected} of ${total} row${total === 1 ? \"\" : \"s\"} selected`",
    "description": ""
  },
  {
    "name": "sortByColumnAsc",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Sort by ${column} ascending`",
    "description": ""
  },
  {
    "name": "sortByColumnDesc",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Sort by ${column} descending`",
    "description": ""
  },
  {
    "name": "sortAscending",
    "type": "string",
    "required": true,
    "default": "Sort ascending",
    "description": ""
  },
  {
    "name": "sortDescending",
    "type": "string",
    "required": true,
    "default": "Sort descending",
    "description": ""
  },
  {
    "name": "clearSort",
    "type": "string",
    "required": true,
    "default": "Clear sort",
    "description": ""
  },
  {
    "name": "sortedAscending",
    "type": "string",
    "required": true,
    "default": "Sorted ascending",
    "description": ""
  },
  {
    "name": "sortedDescending",
    "type": "string",
    "required": true,
    "default": "Sorted descending",
    "description": ""
  },
  {
    "name": "columnActions",
    "type": "string",
    "required": true,
    "default": "Column actions",
    "description": ""
  },
  {
    "name": "hideColumn",
    "type": "string",
    "required": true,
    "default": "Hide column",
    "description": ""
  },
  {
    "name": "showAllColumns",
    "type": "string",
    "required": true,
    "default": "Show all columns",
    "description": ""
  },
  {
    "name": "pinToLeft",
    "type": "string",
    "required": true,
    "default": "Pin to left",
    "description": ""
  },
  {
    "name": "pinToRight",
    "type": "string",
    "required": true,
    "default": "Pin to right",
    "description": ""
  },
  {
    "name": "unpin",
    "type": "string",
    "required": true,
    "default": "Unpin",
    "description": ""
  },
  {
    "name": "reorderColumn",
    "type": "string",
    "required": true,
    "default": "Reorder column",
    "description": ""
  },
  {
    "name": "reorderRow",
    "type": "string",
    "required": true,
    "default": "Reorder row",
    "description": ""
  },
  {
    "name": "pinRow",
    "type": "string",
    "required": true,
    "default": "Pin row",
    "description": ""
  },
  {
    "name": "unpinRow",
    "type": "string",
    "required": true,
    "default": "Unpin row",
    "description": ""
  },
  {
    "name": "resizeColumn",
    "type": "string",
    "required": true,
    "default": "Resize column",
    "description": ""
  },
  {
    "name": "groupByColumn",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Group by ${column}`",
    "description": ""
  },
  {
    "name": "ungroupByColumn",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Ungroup by ${column}`",
    "description": ""
  },
  {
    "name": "groupedBy",
    "type": "string",
    "required": true,
    "default": "Grouped by",
    "description": ""
  },
  {
    "name": "dropToGroupBy",
    "type": "string",
    "required": true,
    "default": "Drag a column here to group by it",
    "description": ""
  },
  {
    "name": "expand",
    "type": "string",
    "required": true,
    "default": "Expand",
    "description": ""
  },
  {
    "name": "collapse",
    "type": "string",
    "required": true,
    "default": "Collapse",
    "description": ""
  },
  {
    "name": "expandAll",
    "type": "string",
    "required": true,
    "default": "Expand all",
    "description": ""
  },
  {
    "name": "collapseAll",
    "type": "string",
    "required": true,
    "default": "Collapse all",
    "description": ""
  },
  {
    "name": "toggleRowExpanded",
    "type": "string",
    "required": true,
    "default": "Toggle row expanded",
    "description": ""
  },
  {
    "name": "columnVisibility",
    "type": "string",
    "required": true,
    "default": "Column visibility",
    "description": ""
  },
  {
    "name": "toggleColumnVisibility",
    "type": "string",
    "required": true,
    "default": "Toggle column visibility",
    "description": ""
  },
  {
    "name": "filterByColumn",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Filter by ${column}`",
    "description": ""
  },
  {
    "name": "clearFilter",
    "type": "string",
    "required": true,
    "default": "Clear filter",
    "description": ""
  },
  {
    "name": "filterMode",
    "type": "string",
    "required": true,
    "default": "Filter mode",
    "description": ""
  },
  {
    "name": "changeFilterMode",
    "type": "string",
    "required": true,
    "default": "Change filter mode",
    "description": ""
  },
  {
    "name": "filterPlaceholder",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Filter ${column}…`",
    "description": ""
  },
  {
    "name": "showColumnFilters",
    "type": "string",
    "required": true,
    "default": "Show filters",
    "description": ""
  },
  {
    "name": "hideColumnFilters",
    "type": "string",
    "required": true,
    "default": "Hide filters",
    "description": ""
  },
  {
    "name": "min",
    "type": "string",
    "required": true,
    "default": "Min",
    "description": ""
  },
  {
    "name": "max",
    "type": "string",
    "required": true,
    "default": "Max",
    "description": ""
  },
  {
    "name": "pickDate",
    "type": "string",
    "required": true,
    "default": "Pick a date",
    "description": ""
  },
  {
    "name": "pickDateRange",
    "type": "string",
    "required": true,
    "default": "Pick a date range",
    "description": ""
  },
  {
    "name": "filterModes",
    "type": "Record<string, string>",
    "required": true,
    "default": "{\n    fuzzy: \"Fuzzy\",\n    contains: \"Contains\",\n    startsWith: \"Starts with\",\n    endsWith: \"Ends with\",\n    equals: \"Equals\",\n    notEquals: \"Not equals\",\n    empty: \"Empty\",\n    notEmpty: \"Not empty\",\n    between: \"Between (exclusive)\",\n    betweenInclusive: \"Between (inclusive)\",\n    greaterThan: \"Greater than\",\n    greaterThanOrEqualTo: \"Greater than or equal to\",\n    lessThan: \"Less than\",\n    lessThanOrEqualTo: \"Less than or equal to\",\n    before: \"Before\",\n    after: \"After\",\n    betweenDates: \"Between\",\n    equalsString: \"Equals\",\n    arrIncludesSome: \"Includes\",\n    equalsBool: \"Equals\",\n  }",
    "description": "Labels for each filter mode, keyed by the `FilterMode` string."
  },
  {
    "name": "search",
    "type": "string",
    "required": true,
    "default": "Search",
    "description": ""
  },
  {
    "name": "searchPlaceholder",
    "type": "string",
    "required": true,
    "default": "Search…",
    "description": ""
  },
  {
    "name": "clearSearch",
    "type": "string",
    "required": true,
    "default": "Clear search",
    "description": ""
  },
  {
    "name": "globalFilterMode",
    "type": "string",
    "required": true,
    "default": "Search mode",
    "description": ""
  },
  {
    "name": "toggleDensity",
    "type": "string",
    "required": true,
    "default": "Toggle density",
    "description": ""
  },
  {
    "name": "densityComfortable",
    "type": "string",
    "required": true,
    "default": "Comfortable",
    "description": ""
  },
  {
    "name": "densityCompact",
    "type": "string",
    "required": true,
    "default": "Compact",
    "description": ""
  },
  {
    "name": "densitySpacious",
    "type": "string",
    "required": true,
    "default": "Spacious",
    "description": ""
  },
  {
    "name": "enterFullscreen",
    "type": "string",
    "required": true,
    "default": "Enter full screen",
    "description": ""
  },
  {
    "name": "exitFullscreen",
    "type": "string",
    "required": true,
    "default": "Exit full screen",
    "description": ""
  },
  {
    "name": "rowsPerPage",
    "type": "string",
    "required": true,
    "default": "Rows per page",
    "description": ""
  },
  {
    "name": "paginationRange",
    "type": "(start: number, end: number, total: number) => string",
    "required": true,
    "default": "(start, end, total) => `${start}–${end} of ${total}`",
    "description": ""
  },
  {
    "name": "goToFirstPage",
    "type": "string",
    "required": true,
    "default": "Go to first page",
    "description": ""
  },
  {
    "name": "goToPreviousPage",
    "type": "string",
    "required": true,
    "default": "Go to previous page",
    "description": ""
  },
  {
    "name": "goToNextPage",
    "type": "string",
    "required": true,
    "default": "Go to next page",
    "description": ""
  },
  {
    "name": "goToLastPage",
    "type": "string",
    "required": true,
    "default": "Go to last page",
    "description": ""
  },
  {
    "name": "rowActions",
    "type": "string",
    "required": true,
    "default": "Row actions",
    "description": ""
  },
  {
    "name": "edit",
    "type": "string",
    "required": true,
    "default": "Edit",
    "description": ""
  },
  {
    "name": "save",
    "type": "string",
    "required": true,
    "default": "Save",
    "description": ""
  },
  {
    "name": "cancel",
    "type": "string",
    "required": true,
    "default": "Cancel",
    "description": ""
  },
  {
    "name": "delete",
    "type": "string",
    "required": true,
    "default": "Delete",
    "description": ""
  },
  {
    "name": "create",
    "type": "string",
    "required": true,
    "default": "Create",
    "description": ""
  },
  {
    "name": "createNewRow",
    "type": "string",
    "required": true,
    "default": "Create new row",
    "description": ""
  },
  {
    "name": "editRow",
    "type": "string",
    "required": true,
    "default": "Edit row",
    "description": ""
  },
  {
    "name": "required",
    "type": "string",
    "required": true,
    "default": "Required",
    "description": ""
  },
  {
    "name": "copy",
    "type": "string",
    "required": true,
    "default": "Copy",
    "description": ""
  },
  {
    "name": "copied",
    "type": "string",
    "required": true,
    "default": "Copied",
    "description": ""
  },
  {
    "name": "cellActions",
    "type": "string",
    "required": true,
    "default": "Cell actions",
    "description": ""
  },
  {
    "name": "export",
    "type": "string",
    "required": true,
    "default": "Export",
    "description": ""
  },
  {
    "name": "exportCsv",
    "type": "string",
    "required": true,
    "default": "Export to CSV",
    "description": ""
  },
  {
    "name": "exportExcel",
    "type": "string",
    "required": true,
    "default": "Export to Excel",
    "description": ""
  },
  {
    "name": "noRecordsToDisplay",
    "type": "string",
    "required": true,
    "default": "No records to display",
    "description": ""
  },
  {
    "name": "loading",
    "type": "string",
    "required": true,
    "default": "Loading…",
    "description": ""
  }
]

export const iconSlots: ApiMember[] = [
  {
    "name": "sortAscending",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowUpLine",
    "description": ""
  },
  {
    "name": "sortDescending",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowDownLine",
    "description": ""
  },
  {
    "name": "sortUnsorted",
    "type": "IconComponent",
    "required": true,
    "default": "RiExpandUpDownLine",
    "description": ""
  },
  {
    "name": "columnActions",
    "type": "IconComponent",
    "required": true,
    "default": "RiMore2Line",
    "description": ""
  },
  {
    "name": "filter",
    "type": "IconComponent",
    "required": true,
    "default": "RiFilterLine",
    "description": ""
  },
  {
    "name": "filterOff",
    "type": "IconComponent",
    "required": true,
    "default": "RiFilterOffLine",
    "description": ""
  },
  {
    "name": "clearAll",
    "type": "IconComponent",
    "required": true,
    "default": "RiListCheck",
    "description": "Clear-sort / show-all reset action."
  },
  {
    "name": "hide",
    "type": "IconComponent",
    "required": true,
    "default": "RiEyeOffLine",
    "description": ""
  },
  {
    "name": "pin",
    "type": "IconComponent",
    "required": true,
    "default": "RiPushpinLine",
    "description": ""
  },
  {
    "name": "pinnedRow",
    "type": "IconComponent",
    "required": true,
    "default": "RiPushpinFill",
    "description": ""
  },
  {
    "name": "unpin",
    "type": "IconComponent",
    "required": true,
    "default": "RiUnpinLine",
    "description": ""
  },
  {
    "name": "group",
    "type": "IconComponent",
    "required": true,
    "default": "RiGroup2Line",
    "description": ""
  },
  {
    "name": "columnVisibility",
    "type": "IconComponent",
    "required": true,
    "default": "RiLayoutColumnLine",
    "description": ""
  },
  {
    "name": "density",
    "type": "IconComponent",
    "required": true,
    "default": "RiLineHeight",
    "description": ""
  },
  {
    "name": "fullscreenEnter",
    "type": "IconComponent",
    "required": true,
    "default": "RiFullscreenLine",
    "description": ""
  },
  {
    "name": "fullscreenExit",
    "type": "IconComponent",
    "required": true,
    "default": "RiFullscreenExitLine",
    "description": ""
  },
  {
    "name": "search",
    "type": "IconComponent",
    "required": true,
    "default": "RiSearchLine",
    "description": ""
  },
  {
    "name": "clear",
    "type": "IconComponent",
    "required": true,
    "default": "RiCloseLine",
    "description": ""
  },
  {
    "name": "pageFirst",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowLeftDoubleLine",
    "description": ""
  },
  {
    "name": "pagePrev",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowLeftSLine",
    "description": ""
  },
  {
    "name": "pageNext",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowRightSLine",
    "description": ""
  },
  {
    "name": "pageLast",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowRightDoubleLine",
    "description": ""
  },
  {
    "name": "expanded",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowDownSLine",
    "description": ""
  },
  {
    "name": "collapsed",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowRightSLine",
    "description": ""
  },
  {
    "name": "dragHandle",
    "type": "IconComponent",
    "required": true,
    "default": "RiDraggable",
    "description": ""
  },
  {
    "name": "edit",
    "type": "IconComponent",
    "required": true,
    "default": "RiPencilLine",
    "description": ""
  },
  {
    "name": "save",
    "type": "IconComponent",
    "required": true,
    "default": "RiCheckLine",
    "description": ""
  },
  {
    "name": "cancel",
    "type": "IconComponent",
    "required": true,
    "default": "RiCloseLine",
    "description": ""
  },
  {
    "name": "export",
    "type": "IconComponent",
    "required": true,
    "default": "RiDownloadLine",
    "description": ""
  },
  {
    "name": "fileCsv",
    "type": "IconComponent",
    "required": true,
    "default": "RiFileTextLine",
    "description": ""
  },
  {
    "name": "fileExcel",
    "type": "IconComponent",
    "required": true,
    "default": "RiFileExcel2Line",
    "description": ""
  },
  {
    "name": "calendar",
    "type": "IconComponent",
    "required": true,
    "default": "RiCalendarLine",
    "description": ""
  }
]
