// AUTO-GENERATED by apps/web/scripts/build-api-docs.mjs — do not edit by hand.
// Regenerate with `pnpm --filter tablecn-web api:build`.

export interface ApiMember {
  name: string
  type: string
  required: boolean
  default: string | null
  description: string
}

export const useDataTableOptions: ApiMember[] = [
  {
    "name": "localization",
    "type": "Partial<DataTableLocalization>",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "icons",
    "type": "Partial<DataTableIcons>",
    "required": false,
    "default": null,
    "description": "Override any subset of the table's icons."
  },
  {
    "name": "defaultDensity",
    "type": "Density",
    "required": false,
    "default": "\"comfortable\"",
    "description": "Initial density. Uncontrolled."
  },
  {
    "name": "defaultShowColumnFilters",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Initially show the filter row. Uncontrolled."
  },
  {
    "name": "isLoading",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Show the loading affordances (progress bar; skeletons when empty; a dimming overlay over existing rows). Toggle each independently below."
  },
  {
    "name": "isSaving",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Show the progress bar for an in-flight save/mutation. Defaults the progress bar on without replacing rows with skeletons."
  },
  {
    "name": "showProgressBars",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Show the top progress bar. Default: `isLoading || isSaving`."
  },
  {
    "name": "showSkeletons",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Replace the body with skeleton rows while empty. Default: `isLoading`."
  },
  {
    "name": "showLoadingOverlay",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Dim existing rows with an overlay while loading. Default: `isLoading`."
  },
  {
    "name": "enableFacetedValues",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Compute faceted unique values / min-max (auto select options + range bounds). Default true; disable to skip the faceted row models."
  },
  {
    "name": "enableColumnActions",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enableColumnFilterModes",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the filter-mode menu adornment on filter fields. Default true."
  },
  {
    "name": "enableFilterMatchHighlighting",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Highlight matched substrings in cells. Default true."
  },
  {
    "name": "enableGlobalFilter",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the expandable global search in the toolbar. Default true."
  },
  {
    "name": "enableGlobalFilterModes",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the global search mode menu (fuzzy/contains/…). Default true."
  },
  {
    "name": "defaultGlobalFilterMode",
    "type": "GlobalFilterMode",
    "required": false,
    "default": "\"fuzzy\"",
    "description": "Initial global search mode. Default \"fuzzy\"."
  },
  {
    "name": "density",
    "type": "Density",
    "required": false,
    "default": null,
    "description": "Controlled density. Pair with `onDensityChange`; omit for uncontrolled (seed the initial value with `defaultDensity`)."
  },
  {
    "name": "onDensityChange",
    "type": "(density: Density) => void",
    "required": false,
    "default": null,
    "description": "Called whenever the density changes (toolbar toggle or programmatic)."
  },
  {
    "name": "isFullscreen",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Controlled full-screen state. Pair with `onIsFullscreenChange`."
  },
  {
    "name": "onIsFullscreenChange",
    "type": "(isFullscreen: boolean) => void",
    "required": false,
    "default": null,
    "description": "Called whenever the full-screen state is toggled."
  },
  {
    "name": "showColumnFilters",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Controlled filter-row visibility. Pair with `onShowColumnFiltersChange`; omit for uncontrolled (seed with `defaultShowColumnFilters`)."
  },
  {
    "name": "onShowColumnFiltersChange",
    "type": "(showColumnFilters: boolean) => void",
    "required": false,
    "default": null,
    "description": "Called whenever the filter row is shown or hidden."
  },
  {
    "name": "globalFilterMode",
    "type": "GlobalFilterMode",
    "required": false,
    "default": null,
    "description": "Controlled global search mode. Pair with `onGlobalFilterModeChange`; omit for uncontrolled (seed with `defaultGlobalFilterMode`)."
  },
  {
    "name": "onGlobalFilterModeChange",
    "type": "(mode: GlobalFilterMode) => void",
    "required": false,
    "default": null,
    "description": "Called whenever the global search mode changes."
  },
  {
    "name": "enableColumnOrdering",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Drag-and-drop column reordering (adds a grip to each header)."
  },
  {
    "name": "enableColumnPinning",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Column pinning (left/right) via the column-actions menu + sticky columns."
  },
  {
    "name": "enableColumnResizing",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Column resizing via an edge drag handle."
  },
  {
    "name": "enableRowOrdering",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Drag-and-drop row reordering (adds a drag-handle column)."
  },
  {
    "name": "enableRowPinning",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Row pinning (top) via a pin toggle in the row-number column."
  },
  {
    "name": "enableRowNumbers",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Adds a leading row-number column."
  },
  {
    "name": "rowNumberMode",
    "type": "\"static\" | \"original\"",
    "required": false,
    "default": "\"static\"",
    "description": "\"static\" tracks the current view (page-aware); \"original\" uses source index."
  },
  {
    "name": "onRowOrderChange",
    "type": "(activeRowId: string, overRowId: string) => void",
    "required": false,
    "default": null,
    "description": "Called on a row drag-and-drop reorder; the consumer reorders its data."
  },
  {
    "name": "enableGrouping",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Row grouping (group-by menu + drop-to-group zone + aggregated group rows)."
  },
  {
    "name": "enableExpanding",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Row expansion (tree sub-rows and/or detail panels). Auto-on with grouping or when `renderDetailPanel`/`getSubRows` is provided."
  },
  {
    "name": "enableStickyFooter",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Pin the footer (aggregation/footer cells) to the bottom of the surface. Default true (matches the sticky header)."
  },
  {
    "name": "renderDetailPanel",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Render an expanding detail panel for each row."
  },
  {
    "name": "enableEditing",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Enable inline editing."
  },
  {
    "name": "editDisplayMode",
    "type": "EditDisplayMode",
    "required": false,
    "default": "\"cell\"",
    "description": "How edits are surfaced. Default \"cell\"."
  },
  {
    "name": "createRowDefaults",
    "type": "Record<string, unknown>",
    "required": false,
    "default": null,
    "description": "Default values for the create form, keyed by column id."
  },
  {
    "name": "enableClickToCopy",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Show a click-to-copy affordance on all cells (per-column override via meta)."
  },
  {
    "name": "onEditCellSave",
    "type": "(props: { row: Row<TData> column: Column<TData, unknown> value: unknown table: DataTableInstance<TData> }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onSaveRow",
    "type": "(props: { row: Row<TData> values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCreateRow",
    "type": "(props: { values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderRowActions",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderCellActionMenuItems",
    "type": "(props: { cell: Cell<TData, unknown> row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderRowActionMenuItems",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Render a kebab menu in the row-actions column. Returns the menu items (e.g. `<DropdownMenuItem>`); injects the actions column automatically."
  },
  {
    "name": "renderColumnActionsMenuItems",
    "type": "(props: { column: Column<TData, unknown> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Append custom items to the bottom of every column-actions menu. Returns the items (e.g. `<DropdownMenuItem>`); a separator is added before them."
  },
  {
    "name": "renderColumnFilterModeMenuItems",
    "type": "(props: { column: Column<TData, unknown> modes: FilterMode[] currentMode: FilterMode onSelect: (mode: FilterMode) => void table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Replace the radio items in a column's filter-mode menu. Render your own items and call `onSelect(mode)` to switch; `modes` is the allowed set."
  },
  {
    "name": "renderGlobalFilterModeMenuItems",
    "type": "(props: { modes: GlobalFilterMode[] currentMode: GlobalFilterMode onSelect: (mode: GlobalFilterMode) => void table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Replace the radio items in the global-search mode menu. Render your own items and call `onSelect(mode)` to switch; `modes` is the allowed set."
  },
  {
    "name": "onRowClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": "Fired when a body row is clicked / double-clicked."
  },
  {
    "name": "onRowDoubleClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCellClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": "Fired when a body cell is clicked / double-clicked."
  },
  {
    "name": "onCellDoubleClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowVirtualization",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Virtualize body rows for large datasets (recommended past ~100 rows). The table surface becomes the scroll container — give it a bounded height via `className`/`style` (defaults to `max-h-[600px]`). Disables row DnD."
  },
  {
    "name": "enableColumnVirtualization",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Virtualize columns for very wide tables. Applies fixed column widths and is not combined with column pinning/ordering."
  },
  {
    "name": "estimateRowHeight",
    "type": "number",
    "required": false,
    "default": "52",
    "description": "Estimated row height (px) for the virtualizer. Default 52."
  },
  {
    "name": "virtualOverscan",
    "type": "number",
    "required": false,
    "default": "8",
    "description": "Extra rows rendered above/below the viewport. Default 8."
  },
  {
    "name": "rowVirtualizerOptions",
    "type": "RowVirtualizerOptions<TData>",
    "required": false,
    "default": null,
    "description": "Partial `@tanstack/react-virtual` options merged into the row virtualizer (overrides the built-in `count`/`estimateSize`/`overscan`/`measureElement`). Accepts an object or a `({ table }) => options` function."
  },
  {
    "name": "columnVirtualizerOptions",
    "type": "ColumnVirtualizerOptions<TData>",
    "required": false,
    "default": null,
    "description": "Partial `@tanstack/react-virtual` options merged into the column virtualizer. Accepts an object or a `({ table }) => options` function."
  },
  {
    "name": "rowVirtualizerInstanceRef",
    "type": "React.RefObject<DataTableRowVirtualizer | null>",
    "required": false,
    "default": null,
    "description": "Ref populated with the row `Virtualizer` instance for imperative control (e.g. `scrollToIndex`). Only set when `enableRowVirtualization`."
  },
  {
    "name": "columnVirtualizerInstanceRef",
    "type": "React.RefObject<DataTableColumnVirtualizer | null>",
    "required": false,
    "default": null,
    "description": "Ref populated with the column `Virtualizer` instance. Only set when `enableColumnVirtualization`."
  },
  {
    "name": "enableExport",
    "type": "boolean",
    "required": false,
    "default": "false",
    "description": "Show a CSV/Excel export menu in the toolbar."
  },
  {
    "name": "exportFileName",
    "type": "string",
    "required": false,
    "default": null,
    "description": "Base file name for exports (no extension). Default \"export\"."
  },
  {
    "name": "enableStickyHeader",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enablePagination",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "positionPagination",
    "type": "\"top\" | \"bottom\" | \"both\" | \"none\"",
    "required": false,
    "default": "\"bottom\"",
    "description": "Where the pagination controls render. Default \"bottom\". \"none\" keeps pagination active but hides the controls."
  },
  {
    "name": "positionGlobalFilter",
    "type": "\"left\" | \"right\" | \"none\"",
    "required": false,
    "default": "\"right\"",
    "description": "Which toolbar region the global search renders in. Default \"right\" (the internal-actions cluster). \"left\" places it next to the title/actions; \"none\" hides it (same as `enableGlobalFilter: false`)."
  },
  {
    "name": "positionToolbarAlertBanner",
    "type": "\"top\" | \"bottom\" | \"none\"",
    "required": false,
    "default": "\"top\"",
    "description": "Where the row-selection alert banner renders. Default \"top\"."
  },
  {
    "name": "positionToolbarDropZone",
    "type": "\"top\" | \"bottom\" | \"both\" | \"none\"",
    "required": false,
    "default": "\"top\"",
    "description": "Where the group-by drop zone renders (grouping only). Default \"top\"."
  },
  {
    "name": "positionActionsColumn",
    "type": "\"first\" | \"last\"",
    "required": false,
    "default": "\"last\"",
    "description": "Position of the auto-injected row-actions column. Default \"last\"."
  },
  {
    "name": "positionExpandColumn",
    "type": "\"first\" | \"last\"",
    "required": false,
    "default": "\"first\"",
    "description": "Position of the auto-injected expand column (tree / detail panel). Default \"first\"."
  },
  {
    "name": "selectAllMode",
    "type": "\"page\" | \"all\"",
    "required": false,
    "default": "\"page\"",
    "description": "Select-all scope for the header checkbox: the current page (\"page\", default) or every row (\"all\")."
  },
  {
    "name": "enableSelectAll",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the select-all checkbox in the selection column header. Default true."
  },
  {
    "name": "enableTopToolbar",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enableBottomToolbar",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "enableDensityToggle",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the density toggle in the toolbar. Default true."
  },
  {
    "name": "enableFullscreenToggle",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the full-screen toggle in the toolbar. Default true."
  },
  {
    "name": "enableToolbarInternalActions",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": "Show the toolbar's internal icon-action cluster (search, filters, column visibility, export, density, full screen). Default true. Hides the whole cluster at once; use the per-item flags for finer control."
  },
  {
    "name": "enableKeyboardNavigation",
    "type": "boolean",
    "required": false,
    "default": "true",
    "description": ""
  },
  {
    "name": "title",
    "type": "React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderToolbarActions",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom content rendered in the top toolbar's left region (next to the title), e.g. bulk-action buttons."
  },
  {
    "name": "renderTopToolbar",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Replace the entire top toolbar with custom content."
  },
  {
    "name": "renderBottomToolbar",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Replace the entire bottom toolbar (pagination region) with custom content."
  },
  {
    "name": "renderToolbarInternalActions",
    "type": "( props: DataTableSlotProps<TData> ) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Replace the top toolbar's internal icon-action cluster with custom content."
  },
  {
    "name": "renderBottomToolbarCustomActions",
    "type": "( props: DataTableSlotProps<TData> ) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom content rendered in the bottom toolbar's left region (next to pagination), e.g. summary text or actions."
  },
  {
    "name": "renderCaption",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Render a `<caption>` for the table (e.g. an accessible summary)."
  },
  {
    "name": "renderEmpty",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  }
]

export const columnOptions: ApiMember[] = [
  {
    "name": "variant",
    "type": "FilterVariant",
    "required": false,
    "default": null,
    "description": "Filter UI variant rendered in the filter row. Defaults to \"text\"."
  },
  {
    "name": "options",
    "type": "DataTableFilterOption[]",
    "required": false,
    "default": null,
    "description": "Options for `select` / `multi-select` filter variants. If omitted for a select-style variant, options are derived from faceted unique values."
  },
  {
    "name": "filterMode",
    "type": "FilterMode",
    "required": false,
    "default": null,
    "description": "Default filter mode for this column (overrides the per-variant default)."
  },
  {
    "name": "enableColumnFilterModes",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Per-column override for the filter-mode menu (defaults to the table)."
  },
  {
    "name": "renderColumnFilter",
    "type": "(props: { column: Column<TData, TValue> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom filter UI for this column (escape hatch). Replaces the variant."
  },
  {
    "name": "columnFilterModeOptions",
    "type": "FilterMode[]",
    "required": false,
    "default": null,
    "description": "Restrict (and order) the filter-mode menu for this column to this subset of modes. Include the column's default mode."
  },
  {
    "name": "enableEditing",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Allow editing this column (defaults to true when table editing is on)."
  },
  {
    "name": "editVariant",
    "type": "EditVariant",
    "required": false,
    "default": null,
    "description": "Inline editor variant. Defaults to \"text\"."
  },
  {
    "name": "editSelectOptions",
    "type": "DataTableFilterOption[]",
    "required": false,
    "default": null,
    "description": "Options for the \"select\" edit variant."
  },
  {
    "name": "renderEditCell",
    "type": "(props: CellRenderProps<TData, TValue>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom inline editor for this column (escape hatch). Replaces the built-in editor while the cell/row is editing; drive the value via `table.cnTable` (`rowDraft`/`setRowDraftValue` or `onEditCellSave`)."
  },
  {
    "name": "renderGroupedCell",
    "type": "( props: CellRenderProps<TData, TValue> ) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom render for this column's group header cell (when grouped)."
  },
  {
    "name": "renderAggregatedCell",
    "type": "( props: CellRenderProps<TData, TValue> ) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom render for this column's aggregated cell (when grouped). Overrides the TanStack `columnDef.aggregatedCell`."
  },
  {
    "name": "renderPlaceholderCell",
    "type": "( props: CellRenderProps<TData, TValue> ) => React.ReactNode",
    "required": false,
    "default": null,
    "description": "Custom render for this column's placeholder cells in grouped rows (cells with no value because another column owns the group). Default: empty."
  },
  {
    "name": "validate",
    "type": "(value: unknown) => string | undefined",
    "required": false,
    "default": null,
    "description": "Validate an edited value; return an error message or undefined if valid."
  },
  {
    "name": "enableClickToCopy",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Show a click-to-copy affordance on this column's cells."
  },
  {
    "name": "align",
    "type": "\"left\" | \"center\" | \"right\"",
    "required": false,
    "default": null,
    "description": "Horizontal alignment applied to the header label and body cells."
  },
  {
    "name": "disableHighlight",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Opt this column out of match highlighting."
  },
  {
    "name": "disableColumnActions",
    "type": "boolean",
    "required": false,
    "default": null,
    "description": "Hide the column-actions menu for this column."
  },
  {
    "name": "label",
    "type": "string",
    "required": false,
    "default": null,
    "description": "Human-readable label for menus when the header is not a plain string."
  }
]

export const tableInstance: ApiMember[] = [
  {
    "name": "localization",
    "type": "DataTableLocalization",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "icons",
    "type": "DataTableIcons",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "density",
    "type": "Density",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setDensity",
    "type": "React.Dispatch<React.SetStateAction<Density>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "isFullscreen",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setIsFullscreen",
    "type": "React.Dispatch<React.SetStateAction<boolean>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "showColumnFilters",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setShowColumnFilters",
    "type": "React.Dispatch<React.SetStateAction<boolean>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "columnFilterModes",
    "type": "Record<string, FilterMode>",
    "required": true,
    "default": null,
    "description": "Active filter mode per column id."
  },
  {
    "name": "setColumnFilterMode",
    "type": "(columnId: string, mode: FilterMode) => void",
    "required": true,
    "default": null,
    "description": "Switch a column's filter mode (resets the value when it becomes invalid)."
  },
  {
    "name": "globalFilterMode",
    "type": "GlobalFilterMode",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setGlobalFilterMode",
    "type": "(mode: GlobalFilterMode) => void",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableGlobalFilter",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableGlobalFilterModes",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "isLoading",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "isSaving",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "showProgressBars",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "showSkeletons",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "showLoadingOverlay",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableFacetedValues",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnActions",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnFilters",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnFilterModes",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableFilterMatchHighlighting",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "columnsWithCustomCell",
    "type": "ReadonlySet<string>",
    "required": true,
    "default": null,
    "description": "Column ids that supply a custom cell renderer (skipped by auto-highlight)."
  },
  {
    "name": "enableColumnOrdering",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnPinning",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnResizing",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowOrdering",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowPinning",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowNumbers",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "rowNumberMode",
    "type": "\"static\" | \"original\"",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "onRowOrderChange",
    "type": "(activeRowId: string, overRowId: string) => void",
    "required": false,
    "default": null,
    "description": "Called on a row drag-and-drop reorder; the consumer reorders its data."
  },
  {
    "name": "enableGrouping",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableExpanding",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableStickyFooter",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "renderDetailPanel",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableEditing",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "editDisplayMode",
    "type": "EditDisplayMode",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "editingCell",
    "type": "EditingCell | null",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "setEditingCell",
    "type": "React.Dispatch<React.SetStateAction<EditingCell | null>>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "editingRowId",
    "type": "string | null",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "isCreating",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "rowDraft",
    "type": "Record<string, unknown>",
    "required": true,
    "default": null,
    "description": "Draft values for the row/modal editor + create form, keyed by column id."
  },
  {
    "name": "setRowDraftValue",
    "type": "(columnId: string, value: unknown) => void",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "beginRowEdit",
    "type": "(row: Row<TData>) => void",
    "required": true,
    "default": null,
    "description": "Enter row/modal editing for a row, seeding the draft from its values."
  },
  {
    "name": "beginCreate",
    "type": "() => void",
    "required": true,
    "default": null,
    "description": "Open the create form, seeding the draft from `createRowDefaults`."
  },
  {
    "name": "cancelEdit",
    "type": "() => void",
    "required": true,
    "default": null,
    "description": "Exit any editing/creating state, discarding the draft."
  },
  {
    "name": "enableClickToCopy",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "onEditCellSave",
    "type": "(props: { row: Row<TData> column: Column<TData, unknown> value: unknown table: DataTableInstance<TData> }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onSaveRow",
    "type": "(props: { row: Row<TData> values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCreateRow",
    "type": "(props: { values: Record<string, unknown> table: DataTableInstance<TData> exit: () => void }) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderRowActions",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderCellActionMenuItems",
    "type": "(props: { cell: Cell<TData, unknown> row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderRowActionMenuItems",
    "type": "(props: { row: Row<TData> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderColumnActionsMenuItems",
    "type": "(props: { column: Column<TData, unknown> table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderColumnFilterModeMenuItems",
    "type": "(props: { column: Column<TData, unknown> modes: FilterMode[] currentMode: FilterMode onSelect: (mode: FilterMode) => void table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderGlobalFilterModeMenuItems",
    "type": "(props: { modes: GlobalFilterMode[] currentMode: GlobalFilterMode onSelect: (mode: GlobalFilterMode) => void table: DataTableInstance<TData> }) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onRowClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onRowDoubleClick",
    "type": "(props: RowEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCellClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "onCellDoubleClick",
    "type": "(props: CellEvent<TData>) => void",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowVirtualization",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableColumnVirtualization",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "estimateRowHeight",
    "type": "number",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "virtualOverscan",
    "type": "number",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "rowVirtualizerOptions",
    "type": "RowVirtualizerOptions<TData>",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "columnVirtualizerOptions",
    "type": "ColumnVirtualizerOptions<TData>",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "rowVirtualizerInstanceRef",
    "type": "React.RefObject<DataTableRowVirtualizer | null>",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "columnVirtualizerInstanceRef",
    "type": "React.RefObject<DataTableColumnVirtualizer | null>",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableExport",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "exportFileName",
    "type": "string",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "enableStickyHeader",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enablePagination",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "positionPagination",
    "type": "\"top\" | \"bottom\" | \"both\" | \"none\"",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "positionGlobalFilter",
    "type": "\"left\" | \"right\" | \"none\"",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "positionToolbarAlertBanner",
    "type": "\"top\" | \"bottom\" | \"none\"",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "positionToolbarDropZone",
    "type": "\"top\" | \"bottom\" | \"both\" | \"none\"",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableRowSelection",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableTopToolbar",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableBottomToolbar",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableDensityToggle",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableFullscreenToggle",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableToolbarInternalActions",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "enableKeyboardNavigation",
    "type": "boolean",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "title",
    "type": "React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderToolbarActions",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderTopToolbar",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderBottomToolbar",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderToolbarInternalActions",
    "type": "( props: DataTableSlotProps<TData> ) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderBottomToolbarCustomActions",
    "type": "( props: DataTableSlotProps<TData> ) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderCaption",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  },
  {
    "name": "renderEmpty",
    "type": "(props: DataTableSlotProps<TData>) => React.ReactNode",
    "required": false,
    "default": null,
    "description": ""
  }
]

export const dataTableProps: ApiMember[] = [
  {
    "name": "table",
    "type": "DataTableInstance<TData>",
    "required": true,
    "default": null,
    "description": ""
  },
  {
    "name": "pageSizeOptions",
    "type": "number[]",
    "required": false,
    "default": null,
    "description": "Page-size options for the bottom pagination control."
  },
  {
    "name": "surfaceClassName",
    "type": "string",
    "required": false,
    "default": null,
    "description": "Extra classes for the scrollable table surface (e.g. a max-height to engage the sticky header/footer or to bound a virtualized list)."
  }
]

export const localizationKeys: ApiMember[] = [
  {
    "name": "selectAll",
    "type": "string",
    "required": true,
    "default": "Select all",
    "description": ""
  },
  {
    "name": "selectRow",
    "type": "string",
    "required": true,
    "default": "Select row",
    "description": ""
  },
  {
    "name": "clearSelection",
    "type": "string",
    "required": true,
    "default": "Clear selection",
    "description": ""
  },
  {
    "name": "rowsSelected",
    "type": "(selected: number, total: number) => string",
    "required": true,
    "default": "(selected, total) => `${selected} of ${total} row${total === 1 ? \"\" : \"s\"} selected`",
    "description": ""
  },
  {
    "name": "sortByColumnAsc",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Sort by ${column} ascending`",
    "description": ""
  },
  {
    "name": "sortByColumnDesc",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Sort by ${column} descending`",
    "description": ""
  },
  {
    "name": "sortAscending",
    "type": "string",
    "required": true,
    "default": "Sort ascending",
    "description": ""
  },
  {
    "name": "sortDescending",
    "type": "string",
    "required": true,
    "default": "Sort descending",
    "description": ""
  },
  {
    "name": "clearSort",
    "type": "string",
    "required": true,
    "default": "Clear sort",
    "description": ""
  },
  {
    "name": "sortedAscending",
    "type": "string",
    "required": true,
    "default": "Sorted ascending",
    "description": ""
  },
  {
    "name": "sortedDescending",
    "type": "string",
    "required": true,
    "default": "Sorted descending",
    "description": ""
  },
  {
    "name": "columnActions",
    "type": "string",
    "required": true,
    "default": "Column actions",
    "description": ""
  },
  {
    "name": "hideColumn",
    "type": "string",
    "required": true,
    "default": "Hide column",
    "description": ""
  },
  {
    "name": "showAllColumns",
    "type": "string",
    "required": true,
    "default": "Show all columns",
    "description": ""
  },
  {
    "name": "pinToLeft",
    "type": "string",
    "required": true,
    "default": "Pin to left",
    "description": ""
  },
  {
    "name": "pinToRight",
    "type": "string",
    "required": true,
    "default": "Pin to right",
    "description": ""
  },
  {
    "name": "unpin",
    "type": "string",
    "required": true,
    "default": "Unpin",
    "description": ""
  },
  {
    "name": "reorderColumn",
    "type": "string",
    "required": true,
    "default": "Reorder column",
    "description": ""
  },
  {
    "name": "reorderRow",
    "type": "string",
    "required": true,
    "default": "Reorder row",
    "description": ""
  },
  {
    "name": "pinRow",
    "type": "string",
    "required": true,
    "default": "Pin row",
    "description": ""
  },
  {
    "name": "unpinRow",
    "type": "string",
    "required": true,
    "default": "Unpin row",
    "description": ""
  },
  {
    "name": "resizeColumn",
    "type": "string",
    "required": true,
    "default": "Resize column",
    "description": ""
  },
  {
    "name": "groupByColumn",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Group by ${column}`",
    "description": ""
  },
  {
    "name": "ungroupByColumn",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Ungroup by ${column}`",
    "description": ""
  },
  {
    "name": "groupedBy",
    "type": "string",
    "required": true,
    "default": "Grouped by",
    "description": ""
  },
  {
    "name": "dropToGroupBy",
    "type": "string",
    "required": true,
    "default": "Drag a column here to group by it",
    "description": ""
  },
  {
    "name": "expand",
    "type": "string",
    "required": true,
    "default": "Expand",
    "description": ""
  },
  {
    "name": "collapse",
    "type": "string",
    "required": true,
    "default": "Collapse",
    "description": ""
  },
  {
    "name": "expandAll",
    "type": "string",
    "required": true,
    "default": "Expand all",
    "description": ""
  },
  {
    "name": "collapseAll",
    "type": "string",
    "required": true,
    "default": "Collapse all",
    "description": ""
  },
  {
    "name": "toggleRowExpanded",
    "type": "string",
    "required": true,
    "default": "Toggle row expanded",
    "description": ""
  },
  {
    "name": "columnVisibility",
    "type": "string",
    "required": true,
    "default": "Column visibility",
    "description": ""
  },
  {
    "name": "toggleColumnVisibility",
    "type": "string",
    "required": true,
    "default": "Toggle column visibility",
    "description": ""
  },
  {
    "name": "filterByColumn",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Filter by ${column}`",
    "description": ""
  },
  {
    "name": "clearFilter",
    "type": "string",
    "required": true,
    "default": "Clear filter",
    "description": ""
  },
  {
    "name": "filterMode",
    "type": "string",
    "required": true,
    "default": "Filter mode",
    "description": ""
  },
  {
    "name": "changeFilterMode",
    "type": "string",
    "required": true,
    "default": "Change filter mode",
    "description": ""
  },
  {
    "name": "filterPlaceholder",
    "type": "(column: string) => string",
    "required": true,
    "default": "(column) => `Filter ${column}…`",
    "description": ""
  },
  {
    "name": "showColumnFilters",
    "type": "string",
    "required": true,
    "default": "Show filters",
    "description": ""
  },
  {
    "name": "hideColumnFilters",
    "type": "string",
    "required": true,
    "default": "Hide filters",
    "description": ""
  },
  {
    "name": "min",
    "type": "string",
    "required": true,
    "default": "Min",
    "description": ""
  },
  {
    "name": "max",
    "type": "string",
    "required": true,
    "default": "Max",
    "description": ""
  },
  {
    "name": "pickDate",
    "type": "string",
    "required": true,
    "default": "Pick a date",
    "description": ""
  },
  {
    "name": "pickDateRange",
    "type": "string",
    "required": true,
    "default": "Pick a date range",
    "description": ""
  },
  {
    "name": "filterModes",
    "type": "Record<string, string>",
    "required": true,
    "default": "{\n    fuzzy: \"Fuzzy\",\n    contains: \"Contains\",\n    startsWith: \"Starts with\",\n    endsWith: \"Ends with\",\n    equals: \"Equals\",\n    notEquals: \"Not equals\",\n    empty: \"Empty\",\n    notEmpty: \"Not empty\",\n    between: \"Between (exclusive)\",\n    betweenInclusive: \"Between (inclusive)\",\n    greaterThan: \"Greater than\",\n    greaterThanOrEqualTo: \"Greater than or equal to\",\n    lessThan: \"Less than\",\n    lessThanOrEqualTo: \"Less than or equal to\",\n    before: \"Before\",\n    after: \"After\",\n    betweenDates: \"Between\",\n    equalsString: \"Equals\",\n    arrIncludesSome: \"Includes\",\n    equalsBool: \"Equals\",\n  }",
    "description": "Labels for each filter mode, keyed by the `FilterMode` string."
  },
  {
    "name": "search",
    "type": "string",
    "required": true,
    "default": "Search",
    "description": ""
  },
  {
    "name": "searchPlaceholder",
    "type": "string",
    "required": true,
    "default": "Search…",
    "description": ""
  },
  {
    "name": "clearSearch",
    "type": "string",
    "required": true,
    "default": "Clear search",
    "description": ""
  },
  {
    "name": "globalFilterMode",
    "type": "string",
    "required": true,
    "default": "Search mode",
    "description": ""
  },
  {
    "name": "toggleDensity",
    "type": "string",
    "required": true,
    "default": "Toggle density",
    "description": ""
  },
  {
    "name": "densityComfortable",
    "type": "string",
    "required": true,
    "default": "Comfortable",
    "description": ""
  },
  {
    "name": "densityCompact",
    "type": "string",
    "required": true,
    "default": "Compact",
    "description": ""
  },
  {
    "name": "densitySpacious",
    "type": "string",
    "required": true,
    "default": "Spacious",
    "description": ""
  },
  {
    "name": "enterFullscreen",
    "type": "string",
    "required": true,
    "default": "Enter full screen",
    "description": ""
  },
  {
    "name": "exitFullscreen",
    "type": "string",
    "required": true,
    "default": "Exit full screen",
    "description": ""
  },
  {
    "name": "rowsPerPage",
    "type": "string",
    "required": true,
    "default": "Rows per page",
    "description": ""
  },
  {
    "name": "paginationRange",
    "type": "(start: number, end: number, total: number) => string",
    "required": true,
    "default": "(start, end, total) => `${start}–${end} of ${total}`",
    "description": ""
  },
  {
    "name": "goToFirstPage",
    "type": "string",
    "required": true,
    "default": "Go to first page",
    "description": ""
  },
  {
    "name": "goToPreviousPage",
    "type": "string",
    "required": true,
    "default": "Go to previous page",
    "description": ""
  },
  {
    "name": "goToNextPage",
    "type": "string",
    "required": true,
    "default": "Go to next page",
    "description": ""
  },
  {
    "name": "goToLastPage",
    "type": "string",
    "required": true,
    "default": "Go to last page",
    "description": ""
  },
  {
    "name": "rowActions",
    "type": "string",
    "required": true,
    "default": "Row actions",
    "description": ""
  },
  {
    "name": "edit",
    "type": "string",
    "required": true,
    "default": "Edit",
    "description": ""
  },
  {
    "name": "save",
    "type": "string",
    "required": true,
    "default": "Save",
    "description": ""
  },
  {
    "name": "cancel",
    "type": "string",
    "required": true,
    "default": "Cancel",
    "description": ""
  },
  {
    "name": "delete",
    "type": "string",
    "required": true,
    "default": "Delete",
    "description": ""
  },
  {
    "name": "create",
    "type": "string",
    "required": true,
    "default": "Create",
    "description": ""
  },
  {
    "name": "createNewRow",
    "type": "string",
    "required": true,
    "default": "Create new row",
    "description": ""
  },
  {
    "name": "editRow",
    "type": "string",
    "required": true,
    "default": "Edit row",
    "description": ""
  },
  {
    "name": "required",
    "type": "string",
    "required": true,
    "default": "Required",
    "description": ""
  },
  {
    "name": "copy",
    "type": "string",
    "required": true,
    "default": "Copy",
    "description": ""
  },
  {
    "name": "copied",
    "type": "string",
    "required": true,
    "default": "Copied",
    "description": ""
  },
  {
    "name": "cellActions",
    "type": "string",
    "required": true,
    "default": "Cell actions",
    "description": ""
  },
  {
    "name": "export",
    "type": "string",
    "required": true,
    "default": "Export",
    "description": ""
  },
  {
    "name": "exportCsv",
    "type": "string",
    "required": true,
    "default": "Export to CSV",
    "description": ""
  },
  {
    "name": "exportExcel",
    "type": "string",
    "required": true,
    "default": "Export to Excel",
    "description": ""
  },
  {
    "name": "noRecordsToDisplay",
    "type": "string",
    "required": true,
    "default": "No records to display",
    "description": ""
  },
  {
    "name": "loading",
    "type": "string",
    "required": true,
    "default": "Loading…",
    "description": ""
  }
]

export const iconSlots: ApiMember[] = [
  {
    "name": "sortAscending",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowUpLine",
    "description": ""
  },
  {
    "name": "sortDescending",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowDownLine",
    "description": ""
  },
  {
    "name": "sortUnsorted",
    "type": "IconComponent",
    "required": true,
    "default": "RiExpandUpDownLine",
    "description": ""
  },
  {
    "name": "columnActions",
    "type": "IconComponent",
    "required": true,
    "default": "RiMore2Line",
    "description": ""
  },
  {
    "name": "filter",
    "type": "IconComponent",
    "required": true,
    "default": "RiFilterLine",
    "description": ""
  },
  {
    "name": "filterOff",
    "type": "IconComponent",
    "required": true,
    "default": "RiFilterOffLine",
    "description": ""
  },
  {
    "name": "clearAll",
    "type": "IconComponent",
    "required": true,
    "default": "RiListCheck",
    "description": "Clear-sort / show-all reset action."
  },
  {
    "name": "hide",
    "type": "IconComponent",
    "required": true,
    "default": "RiEyeOffLine",
    "description": ""
  },
  {
    "name": "pin",
    "type": "IconComponent",
    "required": true,
    "default": "RiPushpinLine",
    "description": ""
  },
  {
    "name": "pinnedRow",
    "type": "IconComponent",
    "required": true,
    "default": "RiPushpinFill",
    "description": ""
  },
  {
    "name": "unpin",
    "type": "IconComponent",
    "required": true,
    "default": "RiUnpinLine",
    "description": ""
  },
  {
    "name": "group",
    "type": "IconComponent",
    "required": true,
    "default": "RiGroup2Line",
    "description": ""
  },
  {
    "name": "columnVisibility",
    "type": "IconComponent",
    "required": true,
    "default": "RiLayoutColumnLine",
    "description": ""
  },
  {
    "name": "density",
    "type": "IconComponent",
    "required": true,
    "default": "RiLineHeight",
    "description": ""
  },
  {
    "name": "fullscreenEnter",
    "type": "IconComponent",
    "required": true,
    "default": "RiFullscreenLine",
    "description": ""
  },
  {
    "name": "fullscreenExit",
    "type": "IconComponent",
    "required": true,
    "default": "RiFullscreenExitLine",
    "description": ""
  },
  {
    "name": "search",
    "type": "IconComponent",
    "required": true,
    "default": "RiSearchLine",
    "description": ""
  },
  {
    "name": "clear",
    "type": "IconComponent",
    "required": true,
    "default": "RiCloseLine",
    "description": ""
  },
  {
    "name": "pageFirst",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowLeftDoubleLine",
    "description": ""
  },
  {
    "name": "pagePrev",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowLeftSLine",
    "description": ""
  },
  {
    "name": "pageNext",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowRightSLine",
    "description": ""
  },
  {
    "name": "pageLast",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowRightDoubleLine",
    "description": ""
  },
  {
    "name": "expanded",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowDownSLine",
    "description": ""
  },
  {
    "name": "collapsed",
    "type": "IconComponent",
    "required": true,
    "default": "RiArrowRightSLine",
    "description": ""
  },
  {
    "name": "dragHandle",
    "type": "IconComponent",
    "required": true,
    "default": "RiDraggable",
    "description": ""
  },
  {
    "name": "edit",
    "type": "IconComponent",
    "required": true,
    "default": "RiPencilLine",
    "description": ""
  },
  {
    "name": "save",
    "type": "IconComponent",
    "required": true,
    "default": "RiCheckLine",
    "description": ""
  },
  {
    "name": "cancel",
    "type": "IconComponent",
    "required": true,
    "default": "RiCloseLine",
    "description": ""
  },
  {
    "name": "export",
    "type": "IconComponent",
    "required": true,
    "default": "RiDownloadLine",
    "description": ""
  },
  {
    "name": "fileCsv",
    "type": "IconComponent",
    "required": true,
    "default": "RiFileTextLine",
    "description": ""
  },
  {
    "name": "fileExcel",
    "type": "IconComponent",
    "required": true,
    "default": "RiFileExcel2Line",
    "description": ""
  },
  {
    "name": "calendar",
    "type": "IconComponent",
    "required": true,
    "default": "RiCalendarLine",
    "description": ""
  }
]
